from __future__ import annotations

import hashlib
import subprocess
from abc import ABC, abstractmethod
from itertools import count
from pathlib import Path

from hackathon_agents.tools.dft_job import DFTJob, DFTResult


class HPCClient(ABC):
    """Abstract HPC interface used by DFTAgent."""

    @abstractmethod
    def submit_job(self, job: DFTJob) -> str:
        """Submit a DFT job and return a backend job id."""

    @abstractmethod
    def get_status(self, job_id: str) -> str:
        """Return current job status."""

    @abstractmethod
    def fetch_results(self, job_id: str) -> DFTResult:
        """Return parsed or stubbed DFT results."""


class MockHPCClient(HPCClient):
    """Offline HPC client that returns deterministic fake DFT results."""

    def __init__(self):
        self._ids = count(1)
        self._jobs: dict[str, DFTJob] = {}

    def submit_job(self, job: DFTJob) -> str:
        job_id = f"hpc-mock-{next(self._ids):04d}"
        self._jobs[job_id] = job
        return job_id

    def get_status(self, job_id: str) -> str:
        return "completed" if job_id in self._jobs else "unknown"

    def fetch_results(self, job_id: str) -> DFTResult:
        if job_id not in self._jobs:
            raise KeyError(f"unknown mock HPC job: {job_id}")
        job = self._jobs[job_id]
        digest = hashlib.sha256(job.model_dump_json().encode("utf-8")).hexdigest()
        offset = int(digest[:6], 16) / 1_000_000.0
        return DFTResult(
            job_id=job_id,
            status="completed",
            energy_hartree=-250.0 - offset,
            frequencies_cm1=[100.0, 250.0, 500.0],
            parsed_ok=True,
            summary=f"Mock DFT result for {job.linked_hypothesis_id}; not a physical calculation.",
        )


class SlurmHPCClient(HPCClient):
    """SLURM backend that writes scripts and optionally calls sbatch.

    By default this client never submits to a cluster.  It only creates the
    submission script, which keeps dry-run mode safe on machines without SLURM
    credentials or project-specific partitions.
    """

    def __init__(
        self,
        *,
        submit_dir: str | Path,
        allow_submit: bool = False,
        submit_command: str = "sbatch",
    ):
        self.submit_dir = Path(submit_dir)
        self.allow_submit = allow_submit
        self.submit_command = submit_command
        self._scripts: dict[str, Path] = {}
        self._ids = count(1)

    def submit_job(self, job: DFTJob) -> str:
        self.submit_dir.mkdir(parents=True, exist_ok=True)
        script_path = self.write_submission_script(job)
        dry_job_id = f"slurm-script-{next(self._ids):04d}"
        self._scripts[dry_job_id] = script_path
        if not self.allow_submit:
            return dry_job_id
        completed = subprocess.run(
            [self.submit_command, str(script_path)],
            check=False,
            capture_output=True,
            text=True,
            timeout=30,
        )
        if completed.returncode != 0:
            raise RuntimeError(f"SLURM submission failed: {completed.stderr.strip()}")
        return completed.stdout.strip() or dry_job_id

    def get_status(self, job_id: str) -> str:
        if job_id in self._scripts:
            return "script_written" if not self.allow_submit else "submitted"
        return "unknown"

    def fetch_results(self, job_id: str) -> DFTResult:
        script = self._scripts.get(job_id)
        if script is None:
            raise KeyError(f"unknown SLURM job id: {job_id}")
        return DFTResult(
            job_id=job_id,
            status=self.get_status(job_id),
            output_files=[str(script)],
            parsed_ok=False,
            summary="SLURM script generated; result parsing is a project-specific stub.",
        )

    def write_submission_script(self, job: DFTJob) -> Path:
        script_path = self.submit_dir / f"{job.id}.slurm"
        calculation_line = _calculation_line(job)
        script = "\n".join(
            [
                "#!/usr/bin/env bash",
                f"#SBATCH --job-name={job.id}",
                "#SBATCH --time=01:00:00",
                "#SBATCH --cpus-per-task=4",
                "#SBATCH --mem=4G",
                "set -euo pipefail",
                "",
                "echo 'DFT submission script generated by Mechanism Discovery Agent Workbench'",
                f"echo 'Reason: {job.reason_for_calculation}'",
                f"cat > {job.id}.inp <<'EOF'",
                calculation_line,
                "",
                "* xyz {charge} {multiplicity}".format(charge=job.charge, multiplicity=job.multiplicity),
                job.molecule_or_structure,
                "*",
                "EOF",
                "echo 'Project-specific ORCA/Gaussian command goes here.'",
                "",
            ]
        )
        script_path.write_text(script, encoding="utf-8")
        return script_path


def _calculation_line(job: DFTJob) -> str:
    solvent = f" CPCM({job.solvent_model})" if job.solvent_model else ""
    task = {
        "optimization": "Opt",
        "frequency": "Freq",
        "single_point": "SP",
        "transition_state": "OptTS Freq",
    }.get(str(job.calculation_type), "Opt")
    return f"! {job.method} {job.basis}{solvent} {task}"
