from __future__ import annotations

from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from hackathon_agents.llm.validators import validate_latex_output
from hackathon_agents.tools.base import error_result, ok_result


class LatexReportInput(BaseModel):
    output_path: str
    title: str = "Scientific Discovery Agent Report"
    user_request: str
    plan: dict[str, Any] | None = None
    candidates: list[dict[str, Any]] = Field(default_factory=list)
    tool_results: list[dict[str, Any]] = Field(default_factory=list)
    critic_notes: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    bibliography_path: str | None = None


def write_latex_report(input_data: LatexReportInput | dict[str, Any]):
    parsed = input_data if isinstance(input_data, LatexReportInput) else LatexReportInput.model_validate(input_data)
    try:
        output = Path(parsed.output_path)
        output.parent.mkdir(parents=True, exist_ok=True)
        rendered = _render_latex(parsed)
        validation = validate_latex_output(rendered)
        validation_data = {
            "ok": validation.ok,
            "errors": validation.errors,
            "warnings": validation.warnings or [],
        }
        if not validation.ok:
            return error_result(
                "LaTeX validation failed: " + "; ".join(validation.errors),
                {"output_path": parsed.output_path, "latex_validation": validation_data},
            )
        output.write_text(validation.normalized, encoding="utf-8")

        artifacts = [str(output)]
        data: dict[str, Any] = {"path": str(output), "latex_validation": validation_data}
        if parsed.bibliography_path:
            bibliography = Path(parsed.bibliography_path)
            bibliography.parent.mkdir(parents=True, exist_ok=True)
            if not bibliography.exists():
                bibliography.write_text("% Add BibTeX entries here.\n", encoding="utf-8")
            artifacts.append(str(bibliography))
            data["bibliography_path"] = str(bibliography)

        return ok_result(data, artifacts)
    except Exception as exc:
        return error_result(str(exc), {"output_path": parsed.output_path})


def _render_latex(report: LatexReportInput) -> str:
    lines = [
        "% Generated by hackathon_agents.tools.latex_writer.",
        "\\documentclass[11pt]{article}",
        "\\usepackage[T1]{fontenc}",
        "\\usepackage[margin=1in]{geometry}",
        "\\usepackage{longtable}",
        "\\usepackage{hyperref}",
        "",
        f"\\title{{{_latex_escape(report.title)}}}",
        "\\author{Hackathon Agents}",
        "\\date{\\today}",
        "",
        "\\begin{document}",
        "\\maketitle",
        "",
        "\\begin{abstract}",
        "This report summarizes a bounded scientific-discovery agent run. "
        "All conclusions should be interpreted as provisional unless independently validated.",
        "\\end{abstract}",
        "",
        "\\section{Request}",
    ]
    _append_paragraph(lines, report.user_request)

    if report.plan:
        _append_plan(lines, report.plan)

    _append_candidates(lines, report.candidates)
    _append_tool_results(lines, report.tool_results)
    _append_list_section(lines, "Critic Notes", report.critic_notes, "No critic notes were recorded.")
    _append_list_section(lines, "Errors and Fallbacks", report.errors, "No errors were recorded.")

    if report.bibliography_path:
        bibliography_stem = Path(report.bibliography_path).with_suffix("").name
        lines.extend(["", "\\bibliographystyle{plain}", f"\\bibliography{{{_latex_escape(bibliography_stem)}}}"])

    lines.extend(["", "\\end{document}", ""])
    return "\n".join(lines)


def _append_plan(lines: list[str], plan: dict[str, Any]) -> None:
    lines.extend(["", "\\section{Plan}"])
    objective = plan.get("objective")
    if objective:
        lines.extend(["\\subsection{Objective}"])
        _append_paragraph(lines, objective)

    assumptions = plan.get("assumptions") or []
    if assumptions:
        lines.extend(["", "\\subsection{Assumptions}", "\\begin{itemize}"])
        for assumption in assumptions:
            lines.append(f"\\item {_latex_escape(assumption)}")
        lines.append("\\end{itemize}")

    steps = plan.get("steps") or []
    if steps:
        lines.extend(["", "\\subsection{Steps}", "\\begin{enumerate}"])
        for step in steps:
            if not isinstance(step, dict):
                lines.append(f"\\item {_latex_escape(step)}")
                continue
            name = step.get("name", "step")
            description = step.get("description", "")
            agent = step.get("agent")
            tool_names = step.get("tool_names") or []
            suffix_parts = []
            if agent:
                suffix_parts.append(f"agent: {agent}")
            if tool_names:
                suffix_parts.append(f"tools: {', '.join(str(tool) for tool in tool_names)}")
            suffix = f" ({'; '.join(suffix_parts)})" if suffix_parts else ""
            lines.append(f"\\item \\textbf{{{_latex_escape(name)}}}. {_latex_escape(description + suffix)}")
        lines.append("\\end{enumerate}")


def _append_candidates(lines: list[str], candidates: list[dict[str, Any]]) -> None:
    lines.extend(["", "\\section{Candidate Molecules}"])
    if not candidates:
        lines.append("No candidate molecules were produced.")
        return

    lines.extend(
        [
            "\\begin{longtable}{p{0.18\\linewidth}p{0.23\\linewidth}rrrr}",
            "Name & SMILES & Mol. wt & LogP & QED & Score \\\\",
            "\\hline",
        ]
    )
    for candidate in candidates:
        descriptors = candidate.get("descriptors", {})
        row = [
            _latex_escape(candidate.get("name") or ""),
            _latex_escape(candidate.get("smiles") or ""),
            _format_value(descriptors.get("mol_wt")),
            _format_value(descriptors.get("logp")),
            _format_value(descriptors.get("qed")),
            _format_value(candidate.get("score")),
        ]
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\end{longtable}")


def _append_tool_results(lines: list[str], tool_results: list[dict[str, Any]]) -> None:
    lines.extend(["", "\\section{Tool Results}"])
    if not tool_results:
        lines.append("No tool results were recorded.")
        return

    lines.extend(["\\begin{itemize}"])
    for record in tool_results:
        tool_name = record.get("tool_name", "tool")
        result = record.get("result", {})
        status = "ok" if result.get("ok") else "failed"
        artifacts = result.get("artifacts") or []
        artifact_text = f"; artifacts: {', '.join(str(artifact) for artifact in artifacts)}" if artifacts else ""
        lines.append(f"\\item \\textbf{{{_latex_escape(tool_name)}}}: {_latex_escape(status + artifact_text)}")
    lines.append("\\end{itemize}")


def _append_list_section(lines: list[str], title: str, items: list[str], empty_text: str) -> None:
    lines.extend(["", f"\\section{{{_latex_escape(title)}}}"])
    if not items:
        lines.append(_latex_escape(empty_text))
        return

    lines.append("\\begin{itemize}")
    for item in items:
        lines.append(f"\\item {_latex_escape(item)}")
    lines.append("\\end{itemize}")


def _append_paragraph(lines: list[str], text: Any) -> None:
    for paragraph in str(text).split("\n\n"):
        cleaned = " ".join(paragraph.splitlines()).strip()
        if cleaned:
            lines.extend(["", _latex_escape(cleaned)])


def _format_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, float):
        return f"{value:.3f}"
    return _latex_escape(value)


def _latex_escape(value: Any) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in str(value))
